### PR TITLE
[rust]sync client settings periodically

### PR DESCRIPTION
**Pull request by glcrazier**
### Which Issue(s) This PR Fixes

Fixes #issue_id

### Brief Description

To align with Java implementations, the rust client should synchronize client settings per 30 seconds by default.

### CODE REVIEW

**Comment by ShadowySpirits** [comment]
This PR contains additional changes beyond the description. Could you please create an issue and provide more details first?

**Comment by glcrazier** [comment]
> This PR contains additional changes beyond the description. Could you please create an issue and provide more details first?

i have removed the additional changes.

**Review by ShadowySpirits — APPROVED** [review]
LGTM

**Review by lizhanhui — DISMISSED** [review]
Looks good

**Review by ShadowySpirits — APPROVED** [review]

**Pull request merged**
