### PR TITLE
[rust]sync topic route every 30 seconds

### PR DESCRIPTION
**Pull request by glcrazier**
### Which Issue(s) This PR Fixes

Fixes #issue_id

### Brief Description

Now the client doesn't update topic route automatically that if topic configuration is updated on server there is no change for client to react on this change other than being restarted. In this PR, the client launches a scheduler to update the route of topics in route table.

### How Did You Test This Change?

I had run e2e test locally that everything is doing fine.

### CODE REVIEW

**Comment by lizhanhui** [comment]
@glcrazier CI failed to pass

**Comment by glcrazier** [comment]
> @glcrazier CI failed to pass

Yes, I will fix it.

**Comment by glcrazier** [comment]
> @glcrazier CI failed to pass

fixed now.

**Comment by glcrazier** [comment]
@lizhanhui have some time to review it?

**Pull request merged**
