### PR TITLE
fix: fix endpoints parsing in Go Client

### PR DESCRIPTION
**Pull request by imp2002**
Fix: #377

### CODE REVIEW

**Comment by imp2002** [comment]
@aaron-ai Hello, it's seems some network error on CI, could you help rerun CI and help review the PR, thanks☺️

**Comment by aaron-ai** [comment]
> @aaron-ai Hello, it's seems some network error on CI, could you help rerun CI and help review the PR, thanks☺️

@imp2002 Could you rebase the master branch to get the latest code? the misspell issue should has been fixed.

**Comment by aaron-ai** [comment]
@imp2002  Great! Extracting multiple addresses from endpoints is the first step in solving this problem.

In fact, the specified implementations of gRPC allow a client/stub to bind to multiple IP addresses. For example, in C++, you can refer to [here](https://grpc.github.io/grpc/core/md_doc_naming.html#:~:text=The%20following%20schemes%20are%20supported%20by%20the%20gRPC%20C%2Dcore%20implementation%2C%20but%20may%20not%20be%20supported%20in%20other%20languages%3A), and in Java, you can refer to the implementation of [IpNameResolverFactory](https://github.com/apache/rocketmq-clients/blob/master/java/client/src/main/java/org/apache/rocketmq/client/java/rpc/IpNameResolverFactory.java). Can you help us confirm how to implement this in Go?

**Comment by imp2002** [comment]
OK, I'll try it.

**Comment by aaron-ai** [comment]
@imp2002 You can comment at #377 , then I will assign it to you.

**Comment by imp2002** [comment]
I am interested in it, could you assign it to me

**Pull request merged**
