### PR TITLE
Golang fix data races

### LINKED ISSUE #294: golang DATA RACE
```golang
// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/rpc_client.go:98
// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/rpc_client.go:98
func (rc *rpcClient) QueryRoute(ctx context.Context, request *v2.QueryRouteRequest) (*v2.QueryRouteResponse, error) {
	rc.activityNanoTime = time.Now() // DATA RACE
	resp, err := rc.msc.QueryRoute(ctx, request)
	sugarBaseLogger.Debugf("queryRoute request: %v, response: %v, err: %v", request, resp, err)
	return resp, err
}

==================
==================
// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/rpc_client.go:137
// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/rpc_client.go:137
func (rc *rpcClient) ReceiveMessage(ctx context.Context, request *v2.ReceiveMessageRequest) (v2.MessagingService_ReceiveMessageClient, error) {
	rc.activityNanoTime = time.Now() // DATA RACE
	resp, err := rc.msc.ReceiveMessage(ctx, request)
	sugarBaseLogger.Debugf("receiveMessage request: %v, err: %v", request, err)
	return resp, err
}

==================
==================

// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/metric.go:166
func (dcmp *defaultClientMeterProvider) isEnabled() bool {
	return dcmp.clientMeter.enabled // DATA RACE
}

// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/metric.go:183
	if !metric.GetOn() {
		dcmp.clientMeter.shutdown()
		sugarBaseLogger.Infof("metric is off, clientId=%s", dcmp.client.GetClientID())
		dcmp.clientMeter = NewDefaultClientMeter(nil, false, nil, dcmp.client.GetClientID()) // DATA RACE
		return
	}

==================
==================

// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/producer_options.go:117
func (ps *producerSettings) IsValidateMessageType() bool {
	return ps.validateMessageType // DATA RACE
}

// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/producer_options.go:163
	}
	ps.validateMessageType = v.Publishing.GetValidateMessageType()
	ps.maxBodySizeBytes = int(v.Publishing.GetMaxBodySize()) // DATA RACE

==================
==================

// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/message_id_codec.go:138
// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/message_id_codec.go:139
	deltaSeconds := deltaSeconds()
	if seconds != deltaSeconds { // DATA RACE
		seconds = deltaSeconds // DATA RACE
	}

==================
==================

// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/producer.go:288 
		if uMsg.pubMsg == nil {
			pubMessage, err = NewPublishingMessage(msg, p.pSetting, txEnabled)  // DATA RACE
			if err != nil {
				return nil, err
			}
		}
// github.com/apache/rocketmq-clients/golang@v0.0.0-20221125070211-5ba0ba13e773/producer_options.go:164
	ps.validateMessageType = v.Publishing.GetValidateMessageType()
	ps.maxBodySizeBytes = int(v.Publishing.GetMaxBodySize())  // DATA RACE
```

### PR DESCRIPTION
**Pull request by Anakin100100**
There are some data races that were described in #294 

Fixes #294

### CODE REVIEW

**Comment by Anakin100100** [comment]
@guyinyou The pr is ready for review. I'm missing the memory safety guarantees of Rust 😞

**Review by guyinyou — COMMENTED** [review]
The license is missing, you can add it at the beginning of the file

**Comment by Anakin100100** [comment]
@guyinyou I added the license to metric_test.go

**Comment by guyinyou** [comment]
> @guyinyou I added the license to metric_test.go

this is a really nice fix

**Pull request merged**
