### PR TITLE
replace nlog with Microsoft.Extensions.Logging

### PR DESCRIPTION
**Pull request by eventhorizon-cli**
replace nlog with Microsoft.Extensions.Logging https://github.com/apache/rocketmq-clients/issues/594

With the `Microsoft.Extensions.Logging`, the sdk can expose an API for configuring LoggerFactory, allowing users to configure logging system freely.

### CODE REVIEW

**Comment by lizhanhui** [comment]
@eventhorizon-cli CI found a few format issues

**Comment by eventhorizon-cli** [comment]
md format issues have been fixed, thanks @lizhanhui

**Comment by aaron-ai** [comment]
Thank you for your suggestion. I think replacing the logging framework is quite reasonable, and more discussion is needed regarding changing the default behavior of log output.

**Comment by lizhanhui** [comment]
> If necessary, an nlog LoggerFactory can configured as the default LoggerFactory to output logs in the current format. But users are allowed to configure their LoggerFactory. @aaron-ai

This sounds reasonable. It would be nice not to change the default behavior in general.

**Review by lizhanhui — APPROVED** [review]

**Pull request merged**
