### PR TITLE
Fix send message error when MessageType unspecified.

### PR DESCRIPTION
**Pull request by echooymxq**
Even if the proxy config set  `enableTopicMessageTypeCheck` false, sending a message always throw an error.

### CODE REVIEW

**Comment by aaron-ai** [comment]
@echooymxq  Producer will get the `settings` from the proxy, which contains the config of `validateMessageType`. you can debug the settings the client received.

**Comment by echooymxq** [comment]
> 



> @echooymxq Producer will get the `settings` from the proxy, which contains the config of `validateMessageType`. you can debug the settings the client received.

@aaron-ai Hi, what i mean is if the proxy return the topic unspecified  message type(in most cases, never will be happen), even though not validate message type, it always send message error. you can also see the golang implementation.

**Comment by aaron-ai** [comment]
@echooymxq Actually route data of each topic should have its message type explicitly, could you describe it clearly?

When does the proxy return unspecified message type?

**Comment by echooymxq** [comment]
@aaron-ai thank your patient reply, there are some potential point ???
```java
// ClusterMetadataService#getTopicMessageType
public TopicMessageType getTopicMessageType(String topic) {
      TopicConfigAndQueueMapping topicConfigAndQueueMapping;
      try {
          topicConfigAndQueueMapping = topicConfigCache.get(topic);
      } catch (Exception e) {
         // Potential point ???
          return TopicMessageType.UNSPECIFIED;
      }
      if (topicConfigAndQueueMapping.equals(EMPTY_TOPIC_CONFIG)) {
          // Potential point ???
          return TopicMessageType.UNSPECIFIED;
      }
      return topicConfigAndQueueMapping.getTopicMessageType();
  }
```

**Comment by echooymxq** [comment]
i will close this pr firstly until you think it's necessary.

**Comment by aaron-ai** [comment]
@echooymxq you could create an issue to track it in [rocketmq's repo](https://github.com/apache/rocketmq). In rocketmq 5.0, route data of each topic should have its message type explicitly, so `UNSPECIFIED` should never be considered.

**Comment by drpmma** [comment]
> @aaron-ai thank your patient reply, there are some potential point ???
> 
> ```java
> // ClusterMetadataService#getTopicMessageType
> public TopicMessageType getTopicMessageType(String topic) {
>       TopicConfigAndQueueMapping topicConfigAndQueueMapping;
>       try {
>           topicConfigAndQueueMapping = topicConfigCache.get(topic);
>       } catch (Exception e) {
>          // Potential point ???
>           return TopicMessageType.UNSPECIFIED;
>       }
>       if (topicConfigAndQueueMapping.equals(EMPTY_TOPIC_CONFIG)) {
>           // Potential point ???
>           return TopicMessageType.UNSPECIFIED;
>       }
>       return topicConfigAndQueueMapping.getTopicMessageType();
>   }
> ```
> 
> even if return the unspecified MessageType, if we set the validateMessageType false, send message maybe success.

The code means it is not TopicConfig in the cache. The getTopicMessageType will return NORMAL type if the type is unset.

**Pull request closed without merging**
